
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Administrator/Downloads/winlibs-x86_64-posix-seh-gcc-15.1.0-mingw-w64msvcrt-13.0.0-r4/mingw64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
...
